# Generated by Django 3.2 on 2023-08-02 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20230725_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='group_id',
            field=models.IntegerField(default=1),
        ),
    ]
