# Generated by Django 3.2 on 2023-08-13 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_node_group_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SortGroup',
            fields=[
                ('group_id', models.IntegerField(primary_key=True, serialize=False)),
                ('sorted_group_ids', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='node',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
    ]
