# Generated by Django 3.2.12 on 2023-09-01 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20230813_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnGroup',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ungroup_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UnGroupId',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ungroup_id', models.IntegerField()),
            ],
        ),
    ]
